export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
// case for 400 reponses
export const USER_LOGIN_FAIL_400 = 'USER_LOGIN_FAIL_400'
export const USER_LOGOUT = 'USER_LOGOUT'